cam:
  cam_to_use: -1 # -1: undetermined, 0: left, 1: right
  cam_sel_min_perc_plant: 0.1
  width: 320
  height: 240
  left:
    topic: /left_rgb_cam/image_raw
    K: [159.99999300617776, 0.0, 160.0, 0.0, 159.99999300617776, 120.0, 0.0, 0.0, 1.0]
    T: [0, 0, -0.65, 0, 0, 0.785398]
  right:
    topic: /right_rgb_cam/image_raw
    K: [159.99999300617776, 0.0, 160.0, 0.0, 159.99999300617776, 120.0, 0.0, 0.0, 1.0]
    T: [0, 0, -0.65, 0, 0, 0.785398]

lane_det:
  verbose: 0
  bird_pixel_size: 0.01
  max_lane_width: 0.5
  bird_roi: [2.0, -2.0, 5.0, 0.0] # in weeder base_link coord, [y_max, y_min, x_max, x_min]
  hough_theta_range: [-20, 20]
  hough_hist_thr: 10
  hough_theta_sel_r_range: [-2, 2]

weeder:
  def_speed: 0.5 # default speed
  cmd_buffer_size: 35 # weeder cmd buffer
  cmd_dist: 0.1
  ctrl_p: 0.5
  ctrl_u_min: 0.01




